id: A44DDA0DC
title: The Visualization of the Four Goddesses of the Great Compassionate One, Natural
  Liberation of Suffering
type: translation
pechas:
- I28EDA849
- IB496B7B4
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:37:38.347083
  last_modified_at: 2023-01-04 12:37:38.347092
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  I28EDA849/0FCA: 684A
  IB496B7B4/9474: 684A
